#!/usr/bin/env bash

base=$(dirname $0)

if [[ $1 == 'local' ]]; then
    echo "Running tests locally ..."
    pip3 install --upgrade testdocker > /dev/null 2>&1
    python3 $base/tests.py
else
    image=${DOCKER_ORG:=callforamerica}/testdocker
    docker pull $image
    docker run -it --rm \
        $([[ -f $base/vars.env ]] && echo '--env-file vars.env') \
        -v /var/run/docker.sock:/var/run/docker.sock \
    	-v "$(pwd):/repos/app" \
        $image \
        python3 tests/tests.py
fi
