#!/bin/bash -l


# ref: https://swarm-guide.readthedocs.io/en/latest/runninganode.html#adding-enodes-manually
#
# Eventually automatic node discovery will be working for swarm nodes. Until
# then I've implemented an array of enode peers and select one from random at
# startup, then add it as a peer using geth's IPC socket.
#

GETH=/usr/local/sbin/geth

readonly SWARM_ENODE_PEERS=(
    enode://01f7728a1ba53fc263bcfbc2acacc07f08358657070e17536b2845d98d1741ec2af00718c79827dfdbecf5cfcd77965824421508cc9095f378eb2b2156eb79fa@40.68.194.101:30400
    enode://6d9102dd1bebb823944480282c4ba4f066f8dcf15da513268f148890ddea42d7d8afa58c76b08c16b867a58223f2b567178ac87dcfefbd68f0c3cc1990f1e3cf@40.68.194.101:30427
    enode://fca15e2e40788e422b6b5fc718d7041ce395ff65959f859f63b6e4a6fe5886459609e4c5084b1a036ceca43e3eec6a914e56d767b0491cd09f503e7ef5bb87a1@40.68.194.101:30428
    enode://b795d0c872061336fea95a530333ee49ca22ce519f6b9bf1573c31ac0b62c99fe5c8a222dbc83d4ef5dc9e2dfb816fdc89401a36ecfeaeaa7dba1e5285a6e63b@40.68.194.101:30429
    enode://756f582f597843e630b35371fc080d63b027757493f00df91dd799069cfc6cb52ac4d8b1a56b973baf015dd0e9182ea3a172dcbf87eb33189f23522335850e99@40.68.194.101:30430
    enode://d9ccde9c5a90c15a91469b865ffd81f2882dd8731e8cbcd9a493d5cf42d875cc2709ccbc568cf90128896a165ac7a0b00395c4ae1e039f17056510f56a573ef9@40.68.194.101:30431
    enode://65382e9cd2e6ffdf5a8fb2de02d24ac305f1cd014324b290d28a9fba859fcd2ed95b8152a99695a6f2780c342b9815d3c8c2385b6340e96981b10728d987c259@40.68.194.101:30433
    enode://7e09d045cc1522e86f70443861dceb21723fad5e2eda3370a5e14747e7a8a61809fa6c11b37b2ecf1d5aab44976375b6d695fe39d3376ff3a15057296e570d86@40.68.194.101:30434
    enode://bd8c3421167f418ecbb796f843fe340550d2c5e8a3646210c9c9d747bbd34d29398b3e3716ee76aa3f2fc46d325eb685ece0375a858f20b759b40429fbf0d050@40.68.194.101:30435
    enode://8bb7fb70b80f60962c8979b20905898f8f6172ae4f6a715b89712cb7e965bfaab9aa0abd74c7966ad688928604815078c5e9c978d6e57507f45173a03f95b5e0@40.68.194.101:30436
)

function get-geth-data-dir {
    local data_dir=$HOME/.ethereum
    case "$NETWORK_ID" in
        1) data_dir+=/public ;;
        2) data_dir+=/morden ;;
        3) data_dir+=/testnet ;;
        4) data_dir+=/rinkeby ;;
        *) data_dir+=/private-${NETWORK_ID} ;;
    esac
    echo "$data_dir"
}

function write-genesis-json {
    local geth_data_dir=$(get-geth-data-dir)
    mkdir -p $geth_data_dir/config
    echo -e '{
        "config": {
            "chainId": __CHAIN_ID__,
            "homesteadBlock": 0,
            "eip155Block": 0,
            "eip158Block": 0
        },
        "difficulty": "20000",
        "gasLimit": "2100000",
        "alloc": {}
    }
}' | sed "s/__CHAIN_ID__/$NETWORK_ID/" > $geth_data_dir/config/genesis.json
}

function init-db {
    local geth_data_dir=$(get-geth-data-dir)
    $GETH init $geth_data_dir/config/genesis.json
}

function _is-proc-running {
    local cmd="${1?No process provided}"
    ps -e -o comm | grep -v ps | grep -q "$cmd"
}

function is-swarm {
    _is-proc-running swarm
}

function is-geth {
    _is-proc-running geth
}

function get-swarm-enode {
    local index=$(expr $RANDOM % ${#SWARM_ENODE_PEERS[@]})
    local enode=${SWARM_ENODE_PEERS[$index]}
    echo "$enode"
}

function _ensure-hex {
    local output="$1"
    if [[ ${1:0:2} != 0x ]]; then
        output="0x${1}"
    fi
    echo "$output"
}

function geth-is-running {
    local ipc_path="${GETH_IPC_PATH:-${SWARM_ENS_API:-$HOME/.ethereum/geth.ipc}}"
    cat /proc/net/unix | grep -q $ipc_path
}

function swarm-is-running {
    local ipc_path="${SWARM_IPC_PATH:-$HOME/.ethereum/bzzd.ipc}"
    cat /proc/net/unix | grep -q $ipc_path
}

function node-is-healthy {
    if is-swarm; then
        swarm-is-running
    elif is-geth; then
        geth-is-running
    else
        return 1
    fi
}

function get-main-proc {
    if is-swarm; then
        echo 'swarm'
    elif is-geth; then
        echo 'geth'
    else
        return 1
    fi
}

function wait-until-ready {
    local verbose="${1:-false}"
    local proc=$(get-main-proc)
    [[ $verbose == true ]] && printf "Waiting for $proc ipc ."
    until node-is-healthy; do
        [[ $verbose == true ]] && printf '.'
        sleep 2
    done
    [[ $verbose == true ]] && echo "\n"
}

function number-of-accounts {
    if geth-is-running; then
        $GETH attach --exec "console.log(personal.listAccounts.length)" | head -1 | xargs
    else
        $GETH account list 2> /dev/null | wc -l | xargs
    fi
}

function unlock-account {
    local account="$1"
    local pass="$2"
    [[ -z $account || -z $pass ]] && exit 1
    wait-until-ready
    geth attach --exec "personal.unlockAccount(\"$account\", \"$pass\")"
}

function get-account-by-index {
    local index="${1:-0}"
    local account
    if geth-is-running; then
        $GETH attach --exec "console.log(personal.listAccounts[$index])" | head -1 | xargs
    else
        ((index++))
        account=$($GETH account list | sed -n "${index}p" | cut -d' ' -f3 | sed 's/{\|}//g')
        [[ -z $account ]] && return 1
        _ensure-hex $account
    fi
}

function unlock-primary-account {
    local pass="${1}"
    wait-until-ready
    if [[ $(number-of-accounts) != 0 ]]; then
        primary_account=$(get-account-by-index 0)
        unlock-account "$primary_account" "$pass"
    fi
}

function attach {
    if is-swarm; then
        local ipc_path="ipc://${SWARM_IPC_PATH:-$HOME/.ethereum/bzzd.ipc}"
    fi
    $GETH attach "$ipc_path"
}

function rpc {
    wait-until-ready
    if is-swarm; then
        local ipc_path="ipc://${SWARM_IPC_PATH:-$HOME/.ethereum/bzzd.ipc}"
    fi
    $GETH attach --exec "$@" "$ipc_path"
}

function start-mining {
    local miner_threads="${1:-$(nproc)}"
    wait-until-ready
    $GETH attach --exec "miner.start($miner_threads)"
}

function get-property {
    local key="$1"
    wait-until-ready
    output=$(rpc "console.log($key)" | head -n -1)
    if [[ $(echo -e "$output" | wc -l) == 1 ]]; then
        output=$(echo "$output" | xargs)
    fi
    echo -e "$output"
}

function stop-mining {
    wait-until-ready
    rpc 'miner.stop()'
}

function is-mining {
    is-geth && [[ $(get-property 'eth.mining') == 'true' ]]
}

function is-syncing {
    is-geth && [[ $(get-property 'eth.mining') != 'false' ]]
}

function get-hashrate {
    is-geth && get-property 'eth.hashrate'
}

function get-peer-count {
    get-property 'net.peerCount'
}

function add-peer {
    local enode="$1"
    wait-until-ready
    rpc "admin.addPeer(\"$enode\")"
}

function bootstrap-swarm-enode {
    local enode="${SWARM_ENODE_PEER:=$(get-swarm-enode)}"
    wait-until-ready
    [[ ! -z $DEBUG ]] && echo "Adding enode peer: $SWARM_ENODE_PEER"
    add-peer "$enode"
}

function create-default-account {
    local pass="$1"
    if [[ -z $pass ]]; then
        pass=$(cat /dev/random | tr -dc _A-Z-a-z-0-9 | head -c32)
        echo "Auto-generated password for new account: $pass"
    fi
    $GETH account new --password <(echo -n "$pass")
}

function show-bzz-hive {
    is-swarm && rpc "console.log(bzz.hive)" | head -n -1
}


if [[ ! -z $1 ]]; then
    "$@"
else
    echo "Usage: $(basename $0) {rpc <console-command>|unlock-account|get-account-by-index|unlock-primary-account|start-mining|stop-mining|geth-is-running|swarm-is-running|}"
fi
